// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAtMoj9KyQtypkn41Oec3bXy3qJB1knig',
    appId: '1:359511091233:web:e3143e8e75099726c25b60',
    messagingSenderId: '359511091233',
    projectId: 'social-media-586cf',
    authDomain: 'social-media-586cf.firebaseapp.com',
    storageBucket: 'social-media-586cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6PilyrSBE7S7qf31MaLU8aWUgDeSz4Uc',
    appId: '1:359511091233:android:3205a3044d05f1dac25b60',
    messagingSenderId: '359511091233',
    projectId: 'social-media-586cf',
    storageBucket: 'social-media-586cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHaa8pWwrfBXybqfLxtKYty0RhGKVImKU',
    appId: '1:359511091233:ios:1ed75aa85cea7d25c25b60',
    messagingSenderId: '359511091233',
    projectId: 'social-media-586cf',
    storageBucket: 'social-media-586cf.appspot.com',
    iosClientId: '359511091233-4aatnq5nsmhbmv9cklg9k9lavn5afunt.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaMaterial',
  );
}
